### ISSUE TITLE
AssertionError: norm(asolve * volt .- sources) < 1.0e-5 in "all-to-one" mode using  the latest development version of Circuiscape. v5.7.1

### ISSUE THREAD

**Issue by luroy** [Circuitscape/Circuitscape.jl#288] opened 2021-05-03 10:23 UTC
Dear all,
I’ve just started using Circuitscape on Julia (and also using Julia). So I apologize in advance if my following comment is due to my unfamiliarity with Circuitscape and/or Julia.
From the same inputs, I ran Circuitscape both one-to-all and all-to-one modes. Everything went well from my one-to-all runtime file (.ini), but I got the following error when running my all-to-one ini file (in R using “JuliaCall” package, but I also have the same error in Julia 1.6.0 console):
```
AssertionError: norm(asolve * volt .- sources) < 1.0e-5
Stacktrace:
  [1] (::Base.var"#837#839")(x::Task)
    @ Base .\asyncmap.jl:177
  [2] foreach(f::Base.var"#837#839", itr::Vector{Any})
    @ Base .\abstractarray.jl:2141
  [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::UnitRange{Int64})
    @ Base .\asyncmap.jl:177
  [4] wrap_n_exec_twice
    @ .\asyncmap.jl:153 [inlined]
  [5] #async_usemap#822
    @ .\asyncmap.jl:103 [inlined]
  [6] #asyncmap#821
    @ .\asyncmap.jl:81 [inlined]
  [7] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Vector{Any}, retry_check::Nothing)
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:126
  [8] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\std
```

Of course, my .ini files were exactly the same, except for the 'scenario' line. 

I think the error I got is due to the latest development version of Circuiscape. v5.7.1 (i.e. Circuitscape v5.7.1 `https://github.com/Circuitscape/Circuitscape.jl.git#master`). Indeed, when I reinstalled Circuitscape via the following command on Julia: `julia> Pkg.add("Circuitscape")`, I compute my all-to-one ini file and did not get an error.

Hoping it can be useful! 

Léa

**Comment by ranjanan** [comment] 2021-05-21 19:10
@luroy could you please post your files in a dropbox / google drive so I can take a look?

**Comment by vlandau** [comment] 2021-05-26 17:38
@ranjanan I wonder if we should use a relative tolerance for satisfying the `@assert` statement instead of absolute?

**Comment by vlandau** [comment] 2021-05-26 21:58
This problem is also triggered in Omniscape, but only when using 32-bit (single precision). @luroy would you happen to also be using `precision = single` in your INI file? If so, you may solve the problem at least temporarily by using `precision = double`.

@ranjanan it seems to be triggered from [this test](https://github.com/Circuitscape/Omniscape.jl/blob/vl/cholmod/test/runtests.jl#L117) on the `vl/cholmod` branch, and I have confirmed that when I alter the test input to tell Circuitscape to use 64-bit instead, the error is not triggered. Maybe we need to set a higher tolerance for the `@assert` statement when using single precision, but you may want to do some digging first.

**Comment by vlandau** [comment] 2021-06-01 20:12
@luroy we've issued a patch release that should fix the problem you were having. Run `using Pkg; Pkg.update("Circuitscape")` in your Julia terminal to get this latest version. I'm going to close this issue, but please feel free to reopen it if you find the problem persisting in Circuitscape v5.8.1!

**Closed by vlandau** 2021-06-01 20:12 UTC
