### ISSUE TITLE
Variable solve times

### ISSUE THREAD

**Issue by wpeterman** [Circuitscape/Circuitscape.jl#129] opened 2018-06-14 19:50 UTC
I'm working with CS.jl in Windows, and have been calling it from R using JuliaCall. I've been running some small scale tests, and have encountered some seemingly odd behavior. When repeatedly solving for 4 points on a small raster (2500 nodes), the task sometimes solves in less than one second:

`[2018-06-14T15:45:48 | info | root]: Precision used: Double
[2018-06-14T15:45:48 | info | root]: Reading maps
[2018-06-14T15:45:48 | info | root]: Resistance/Conductance map has 2500 nodes
[2018-06-14T15:45:48 | info | root]: Solver used: AMG accelerated by CG
[2018-06-14T15:45:48 | info | root]: Graph has 2500 nodes, 4 focal points and 1 connected components
[2018-06-14T15:45:48 | info | root]: Total number of pair solves = 6
[2018-06-14T15:45:48 | info | root]: Triggering resistance calculation shortcut
[2018-06-14T15:45:48 | info | root]: Total number of pair solves has been reduced to 3 
[2018-06-14T15:45:48 | info | root]: Time taken to construct preconditioner = 0.002524242 seconds
[2018-06-14T15:45:48 | info | root]: Time taken to construct local nodemap = 0.000192155 seconds
[2018-06-14T15:45:48 | info | root]: Solving pair 1 of 3
[2018-06-14T15:45:48 | info | root]: Time taken to solve linear system = 0.01385796 seconds
[2018-06-14T15:45:48 | info | root]: Solving pair 2 of 3
[2018-06-14T15:45:48 | info | root]: Time taken to solve linear system = 0.011062591 seconds
[2018-06-14T15:45:48 | info | root]: Solving pair 3 of 3
[2018-06-14T15:45:48 | info | root]: Time taken to solve linear system = 0.011541268 seconds
[2018-06-14T15:45:48 | info | root]: Time taken to complete job = 0.048522817`

But sometimes minutes to run:
`[2018-06-14T15:45:48 | info | root]: Precision used: Double
[2018-06-14T15:45:48 | info | root]: Reading maps
[2018-06-14T15:45:48 | info | root]: Resistance/Conductance map has 2500 nodes
[2018-06-14T15:45:48 | info | root]: Solver used: AMG accelerated by CG
[2018-06-14T15:45:48 | info | root]: Graph has 2500 nodes, 4 focal points and 1 connected components
[2018-06-14T15:45:48 | info | root]: Total number of pair solves = 6
[2018-06-14T15:45:48 | info | root]: Triggering resistance calculation shortcut
[2018-06-14T15:45:48 | info | root]: Total number of pair solves has been reduced to 3 
[2018-06-14T15:45:48 | info | root]: Time taken to construct preconditioner = 0.002756596 seconds
[2018-06-14T15:45:48 | info | root]: Time taken to construct local nodemap = 0.000189874 seconds
[2018-06-14T15:45:48 | info | root]: Solving pair 1 of 3
[2018-06-14T15:46:34 | info | root]: Time taken to solve linear system = 46.273509966 seconds
[2018-06-14T15:46:34 | info | root]: Solving pair 2 of 3
[2018-06-14T15:47:21 | info | root]: Time taken to solve linear system = 46.609233071 seconds
[2018-06-14T15:47:21 | info | root]: Solving pair 3 of 3
[2018-06-14T15:48:07 | info | root]: Time taken to solve linear system = 46.15073924 seconds
[2018-06-14T15:48:07 | info | root]: Time taken to complete job = 139.047756763`

The only thing different between these runs is the resistance values in the surface. I've never encountered this behavior with CIRCUITSCAPE, or with other resistance distance methods (e.g., `commuteDistance `and `costDistance `from the R package `gdistance`). Thoughts?

Pkg.status("Circuitscape")
5.2.1 master

julia v. 0.6.3

Thanks!

**Comment by ViralBShah** [comment] 2018-06-14 20:50
Could you upload the files somewhere for us to download and reproduce?  Are you running it on your laoptop? How much memory?

**Comment by ranjanan** [comment] 2018-06-15 07:38
Yes, could you upload the files to a drop box or Google Drive location, enable sharung and paste the link here please? It would help me debug.

**Comment by wpeterman** [comment] 2018-06-15 15:38
Here is a link to some example files:
https://drive.google.com/open?id=1OtiSZsubtN47ydfOKZf0mAcuM1eEtuEf

I've been running these on a Desktop (i7 3.6 GHz; 24 GB RAM).

There is also a [.txt](https://drive.google.com/open?id=1YnoJlndZquu53ravpgQPRRJV87gJnQTy) file with the WARNING message that is printed when I use CS.jl.

**Comment by wpeterman** [comment] 2018-06-21 15:49
Curious to know if you all had any insights regarding this issue (or if you were able to recreate the issue). Happy to provide more examples or more detail concerning my implementation, if it will be of help.

**Comment by ranjanan** [comment] 2018-06-21 15:58
@wpeterman I just ran the `julia_quickrun` example multiple times straight from Julia and didn't see any variability in solve time. But I ran this on my Mac. Let me run this on a Windows laptop and get back to you.

**Comment by wpeterman** [comment] 2018-06-21 16:03
`julia_longrun` should be the problem surface.

**Comment by ranjanan** [comment] 2018-06-21 16:31
Oh my bad, I think I can see it now. I'll get back to you ASAP

**Comment by ranjanan** [comment] 2018-06-21 16:39
Just as a note, the warning has been fixed in #130

**Comment by wpeterman** [comment] 2018-06-26 12:30
@ranjanan
Has your rounding solution been implemented? If so, what needs to be done to update the package and/or dependencies?
Thanks for your time and effort on this!

**Comment by ranjanan** [comment] 2018-06-27 14:48
Hi @wpeterman, I implemented it on a branch called `round` over here. You can access it by doing: 

```julia
Pkg.checkout("Circuitscape", "round")
```
and then restarting Julia. 

Could you confirm that this works?

Thank you.

**Comment by wpeterman** [comment] 2018-06-27 15:49
I get the following error:

> INFO: Checking out Circuitscape round...
> Error: Error happens in Julia.
> GitError(Code:ERROR, Class:Merge, There is no tracking information for the current branch.)
> Stacktrace:
>  [1] (::Base.LibGit2.##117#125{Base.LibGit2.GitRepo})(::Base.LibGit2.GitReference) at .\libgit2\libgit2.jl:709
>  [2] with(::Base.LibGit2.##117#125{Base.LibGit2.GitRepo}, ::Base.LibGit2.GitReference) at .\libgit2\types.jl:608
>  [3] #merge!#109(::String, ::String, ::Bool, ::Base.LibGit2.MergeOptions, ::Base.LibGit2.CheckoutOptions, ::Function, ::Base.LibGit2.GitRepo) at .\libgit2\libgit2.jl:706
>  [4] (::Base.#kw##merge!)(::Array{Any,1}, ::Base.#merge!, ::Base.LibGit2.GitRepo) at .\<missing>:0
>  [5] (::Base.Pkg.Entry.##16#18{String,String,Bool,Bool})(::Base.LibGit2.GitRepo) at .\pkg\entry.jl:230
>  [6] transact(::Base.Pkg.Entry.##16#18{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at .\libgit2\libgit2.jl:882
>  [7] with(::Base.Pkg.Entry.##15#17{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:608
>  [8] checkout(::String, ::String, ::Bool

**Comment by ranjanan** [comment] 2018-06-27 16:39
Okay, can you try: 
```
Pkg.checkout("Circuitscape") 
Pkg.checkout("Circuitscape", "round") 
```
in that order?

**Comment by wpeterman** [comment] 2018-06-28 13:34
Almost! The 'round' branch efficiently solved several thousand different scenarios with the standard solver as well as cholmod. I did encounter one problematic surface ([files here](https://drive.google.com/open?id=19k2VBctu0wc1uqKO4J1V4B-64RyBjTZZ))

**Comment by wpeterman** [comment] 2018-07-05 19:56
Hi @ranjanan 
Just checking in to see if you had any insights about the problematic surface I encountered with the 'round' branch. Thanks!

**Comment by ranjanan** [comment] 2018-07-17 08:31
@wpeterman Sorry about the late response time. Been moving cities and it's been hard getting some time to work. #134 should have fixed all these issues. Could you please check how this runs on all your problems? Thanks.

**Comment by ranjanan** [comment] 2018-07-17 08:32
You should first do a `Pkg.checkout("Circuitscape", "master")` first if you're already on the `round` branch

**Comment by wpeterman** [comment] 2018-07-17 17:06
@ranjanan 
No worries about the delay. I generated several scenarios that were slow to solve. Some examples are [here](https://drive.google.com/open?id=1sJvD0RSDZ3FBMoWQaV5JHsUB-L3NbxaT).

`Pkg.status("Circuitscape")
– Circuitscape          5.2.1+          round`

**Comment by ranjanan** [comment] 2018-07-17 17:09
@wpeterman It looks like you're on the `round` branch. Could you get on the `master` branch and check if they solve faster?

**Comment by ranjanan** [comment] 2018-07-17 17:11
Also, thank you so much for the nice collection of problems! Do you mind if I include any of them as tests on the repo?

**Comment by ranjanan** [comment] 2018-07-17 17:18
Also I believe there should be another column in your points file on the link

**Comment by ranjanan** [comment] 2018-07-17 17:24
I just added a leading column `1, 2, 3, 4, 5` in your points file. I hope that's okay. On the master branch these seem to solve. Could you please check, @wpeterman? Thank you!

**Comment by wpeterman** [comment] 2018-07-17 18:40
Sorry for my confusion. I didn't realize that the fix had been merged with the master. Several hundred scenarios seem to all solve fine now, thanks! Feel free to use any of my 'problems' as tests.

**Comment by ranjanan** [comment] 2018-07-18 17:18
@wpeterman Thank you! Could I ask you for one more favour please? Could you share the results of your benchmarking, especially if you've done it on a large problem? I would request your permission to quote these results on a presentation I'm giving about the package.

**Closed by ranjanan** 2018-07-18 17:18 UTC

**Comment by ViralBShah** [comment] 2018-07-20 12:57
It would be good to have the example where the speed advantage of CS.jl is the smallest, so that we can try figure out what is happening under the hood.

**Comment by wpeterman** [comment] 2018-07-20 14:01
[Here are files](https://drive.google.com/open?id=1h59ulPj4rxtfaFCeEArkN_bpQYFWhl_T) for testing 10, 50, & 100 points on a 500x500 grid, including a single run Benchmark times comparing CIRCUITSCAPE, CS.jl, and commuteDistance from the R package gdistance.
