### ISSUE TITLE
AssertErrors for several users -- norm(G * v - curr) < 1e-6 check failing

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Circuitscape.jl#305] opened 2021-07-23 22:32 UTC
I've had at least three Omniscape users confront errors related to the `@assert norm(G * v - curr) < <some tolerance>` check after Circuitscape gets a solution. There are currently two open issues in Omniscape.jl, [here](https://github.com/Circuitscape/Omniscape.jl/issues/99), and [here](https://github.com/Circuitscape/Omniscape.jl/issues/100). Something must be going on with the solvers that Circuitscape is using. The error occurs regardless of whether the user specifies CG+AMG or CHOLMOD as the solver.

A few things are still needed:
- Determine if Omniscape is indeed using the CHOLMOD server (there have been reports of that solver not having improved speed over CG+AMG, see [issue 101 for Omniscape.jl](https://github.com/Circuitscape/Omniscape.jl/issues/101)). In theory because this is a direct solver, shouldn't the matrix norm be 0 (unless it's imperfect due to precision limitations)?
- Reproduce the error -- a lot of the problems are occurring for very large problems, but presumably only a few actual moving window iterations in Omniscape. I can try to work on reproducing the error for a problem of manageable size

I wanted to open this issue despite the above not being resolved just to get things in motion. Hopefully we can figure this out!

**Comment by vlandau** [comment] 2021-07-26 23:06
Omniscape is indeed correctly using the CHOLMOD solver. Solve times were much faster.

**Comment by ranjanan** [comment] 2021-08-05 21:29
@vlandau I just need the files so I can reproduce this issue locally and debug. I have commented on both those threads.

**Comment by vlandau** [comment] 2021-08-06 16:04
Sounds good -- a colleague of mine ran into the same issue as well, so I can also try to track down his inputs. He was out this week but back Monday.

**Comment by ranjanan** [comment] 2021-08-09 20:01
Closing this because both related Omniscape issues are now closed.

**Closed by ranjanan** 2021-08-09 20:01 UTC
Labels: bug, high-priority
