### ISSUE TITLE
ncol warning

### ISSUE THREAD

**Issue by linhunt** [Circuitscape/Circuitscape.jl#285] opened 2021-03-24 16:01 UTC
I was running Circuitscape using ascii files and I received an error message that said
"warning: 2021-03-24 10:56:38 : ncols is not the same" 

the program is still running but I am not sure what this warning means. The focal nodes layer was derived from the resistance layer so they should be the same extent and grid size.

**Comment by vlandau** [comment] 2021-08-10 21:46
@linhunt I think this must be because the width/height of your raster inputs are not the same. If you look at the raster information from a GIS, are you able to find the exact number of columns and rows in each?

**Comment by linhunt** [comment] 2021-08-11 17:49
Hi Vincent,

I am in and out of the office this week but will get you the exact numbers hopefully next week. do the inputs need to be perfect squares? This has never been an issue in the past. We are having an issue with the newest version of Omniscape where we keep getting errors in our runs with larger blocks and radii that says there are negative or zero values. This does not occur in our small radii runs.

Thanks,
Lindsay
________________________________
From: Vincent Landau ***@***.***>
Sent: Tuesday, August 10, 2021 4:46 PM
To: Circuitscape/Circuitscape.jl ***@***.***>
Cc: Hunt, Lindsay E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Circuitscape/Circuitscape.jl] ncol warning (#285)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@linhunt<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinhunt&data=04%7C01%7Clhunt%40usgs.gov%7C3905cf0e2f5e4684f67308d95c4862cb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642288230789141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zd5XG1fRFhwk8FEcDdRzAnHOi6SGbWk5hkWVbLGYwcI%3D&reserved=0> I think this must be because the width/height of your raster inputs are not the same. If you look at the raster information from a GIS, are you able to find the exact number of columns and rows in each?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCircuitscape%2FCircuitscape.jl%2Fissues%2F285%23issuecomment-896335329&data=04%7C01%7Clhunt%40usgs.gov%7C3905cf0e2f5e4684f67308d95c4862cb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642288230789141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1oGaGdAcuj6EoIq8NvfnZntVw3XyI%2BJF6pWuNQ2vnGc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJWIV5CHNYGK7Y2HSUMFW4TT4GM3ZANCNFSM4ZXR2PIA&data=04%7C01%7Clhunt%40usgs.gov%7C3905cf0e2f5e4684f67308d95c4862cb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642288230799097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AGAVt8K%2BFfztH%2BvZzDIPxj7OzABxGtpZlv%2FSti5thSk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clhunt%40usgs.gov%7C3905cf0e2f5e4684f67308d95c4862cb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642288230799097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4lewR3yuVohnEgKeLOqw%2BLHESBkLfIQb5QRYTGMJ1WI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Clhunt%40usgs.gov%7C3905cf0e2f5e4684f67308d95c4862cb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642288230809060%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HyC6RgR4018kqGOr4dWnmMw4ypNtAvN%2BM4nq5wORMJ4%3D&reserved=0>.

**Comment by vlandau** [comment] 2021-08-11 19:38
They do not need to be perfect squares. They just need to to have the same exact dimensions. Hopefully we'll be able to figure this out once you look into the exact dimensions.

**Comment by linhunt** [comment] 2021-08-11 20:04
So this is why I am a little confused, I only have one raster input. So there shouldn't have to be any matching of sizes.
________________________________
From: Vincent Landau ***@***.***>
Sent: Wednesday, August 11, 2021 2:38 PM
To: Circuitscape/Circuitscape.jl ***@***.***>
Cc: Hunt, Lindsay E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Circuitscape/Circuitscape.jl] ncol warning (#285)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



They do not need to be perfect squares. They just need to to have the same exact dimensions. Hopefully we'll be able to figure this out once you look into the exact dimensions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCircuitscape%2FCircuitscape.jl%2Fissues%2F285%23issuecomment-897098478&data=04%7C01%7Clhunt%40usgs.gov%7C34fa79360410471c1d7a08d95cffab63%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643087745387113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UvoZz0RlR9yYjTETc4lctUNFLXHUdhJP6NeC4ktl%2BMU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJWIV5HAZKJBANZ3JKO6OQ3T4LGTTANCNFSM4ZXR2PIA&data=04%7C01%7Clhunt%40usgs.gov%7C34fa79360410471c1d7a08d95cffab63%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643087745397071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y77iI9LabED7H31ijTZ1WUxIXH5XojWw3b4GMQZoNZc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clhunt%40usgs.gov%7C34fa79360410471c1d7a08d95cffab63%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643087745397071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zdnBrb2kyjBl1EbIdtCKNh1JxlS2J%2FyOIrqO6e6noGw%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Clhunt%40usgs.gov%7C34fa79360410471c1d7a08d95cffab63%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643087745407028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KLuyuojJNi3qMdg5K5mFdNt%2BO62obeMBIZBQBgXmRcU%3D&reserved=0>.

**Comment by vlandau** [comment] 2021-08-11 20:06
If you are running Circuitscape, you will need two rasters -- one for resistance, and another for the locations of the nodes to connect.

**Comment by linhunt** [comment] 2021-08-23 14:14
Hi Vincent,

Sorry for the delay in my response! We have been trying to run omniscape not Circuitscape where we have just one input file that is the resistance. We have successfully run this exact file with a smaller block size and search radius. We're just getting this "distance matrices must be symmetrical" error message. The number of columns, rows is 36681 (c), 24902(r). If it would be easier to discuss this over the phone (I know you are incredibly busy) I am open to that.

Thank you,
Lindsay
________________________________
From: Vincent Landau ***@***.***>
Sent: Wednesday, August 11, 2021 3:06 PM
To: Circuitscape/Circuitscape.jl ***@***.***>
Cc: Hunt, Lindsay E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Circuitscape/Circuitscape.jl] ncol warning (#285)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



If you are running Circuitscape, you will need two rasters -- one for resistance, and another for the locations of the nodes to connect.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCircuitscape%2FCircuitscape.jl%2Fissues%2F285%23issuecomment-897115388&data=04%7C01%7Clhunt%40usgs.gov%7C20c4d780db21422e96c308d95d03dc7d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643093434552862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZBHV8wI%2BkQadFCBH5aHnaopFRKLudGOGe9Y%2Ff6BW0lI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJWIV5DTG6PEIHO3O6JA7NLT4LJ3PANCNFSM4ZXR2PIA&data=04%7C01%7Clhunt%40usgs.gov%7C20c4d780db21422e96c308d95d03dc7d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643093434552862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XT56HCc1gE8HQ6diY0QfM9VN7d33Xk2uK1ucq0DjKIo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clhunt%40usgs.gov%7C20c4d780db21422e96c308d95d03dc7d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643093434552862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RhvSRb3kYJiuk1tQc7Ps4LvUGliRo84BFmGxWGXm8BI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Clhunt%40usgs.gov%7C20c4d780db21422e96c308d95d03dc7d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637643093434562818%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D4zBHuzh0Ny8%2FsoW3QTE7BkdiMWUdC13DxkA7gRxz1c%3D&reserved=0>.

**Comment by vlandau** [comment] 2021-08-23 16:12
So which error are you getting, `ncols is not the same` or `distance matrices must be symmetrical`? If it's the latter, we have a similar issue in Circuitscape/Omniscape.jl/issues/102, but yours might be easier to debug if it's a smaller problem. Would you mind posting the full stacktrace here in a code block?

**Comment by linhunt** [comment] 2021-08-23 16:13
Sure, what is a code block?
________________________________
From: Vincent Landau ***@***.***>
Sent: Monday, August 23, 2021 11:12 AM
To: Circuitscape/Circuitscape.jl ***@***.***>
Cc: Hunt, Lindsay E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Circuitscape/Circuitscape.jl] ncol warning (#285)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



So which error are you getting, ncols is not the same or distance matrices must be symmetrical? If it's the latter, we have a similar issue in Circuitscape/Omniscape.jl/issues/102<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCircuitscape%2FOmniscape.jl%2Fissues%2F102&data=04%7C01%7Clhunt%40usgs.gov%7C53a7ff3d258c4e286e7108d96650dd34%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637653319767880127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FEX1O6u3F7lazf0wASHgyxSpyY1mtcMnQAH%2BErIIQFA%3D&reserved=0>, but yours might be easier to debug if it's a smaller problem. Would you mind posting the full stacktrace here in a code block?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCircuitscape%2FCircuitscape.jl%2Fissues%2F285%23issuecomment-903915319&data=04%7C01%7Clhunt%40usgs.gov%7C53a7ff3d258c4e286e7108d96650dd34%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637653319767880127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fqYFyfD%2FCxSJRfEZgEC%2BNCqIPVyAxMUKRZK%2Bg88DN0M%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJWIV5GCMTNS5AI4RRX6AVDT6JXOBANCNFSM4ZXR2PIA&data=04%7C01%7Clhunt%40usgs.gov%7C53a7ff3d258c4e286e7108d96650dd34%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637653319767890083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=375CvLYZeHEijAxmCLETs%2B6d61knic9a3ouSarUruaE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clhunt%40usgs.gov%7C53a7ff3d258c4e286e7108d96650dd34%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637653319767890083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bwq2dX1FGIlzQ3M0AdxoxxsCeZixryYNXsnDCFAupfk%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Clhunt%40usgs.gov%7C53a7ff3d258c4e286e7108d96650dd34%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637653319767900040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Szsp3O%2Bj0WU7MQgnD1uUjAZLMvYDzfsoO8T%2F%2FWozodA%3D&reserved=0>.

**Comment by vlandau** [comment] 2021-08-23 16:21
There's a good example [here](https://guides.github.com/features/mastering-markdown/#examples). Just click "code" to access it.

**Comment by linhunt** [comment] 2021-08-30 16:04
I am not sure I am doing this correctly, but this is the distance matrices must be symmetrical error stack trace.
,
Adjacency / distance matrices must be symmetric
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] SimpleWeightedGraph at C:\Users\rgrundel\.julia\packages\SimpleWeightedGraphs\IDzOp\src\simpleweightedgraph.jl:16 [inlined]
 [3] SimpleWeightedGraph at C:\Users\rgrundel\.julia\packages\SimpleWeightedGraphs\IDzOp\src\simpleweightedgraph.jl:27 [inlined]
 [4] compute_advanced_data(::Circuitscape.RasData{Float64,Int64}, ::Circuitscape.RasterFlags, ::Dict{String,String}) at C:\Users\rgrundel\.julia\packages\Circuitscape\9x9VD\src\raster\advanced.jl:56
 [5] calculate_current(::Array{Union{Missing, Float64},2}, ::Array{Union{Missing, Float64},2}, ::Array{Float64,2}, ::Circuitscape.RasterFlags, ::Dict{String,String}, ::DataType) at C:\Users\rgrundel\.julia\packages\Omniscape\UilaE\src\utils.jl:360
 [6] solve_target!(::Int64, ::Int64, ::Dict{String,Int64}, ::Array{Float64,2}, ::Array{Union{Missing, Float64},2}, ::Array{Union{Missing, Float64},2}, ::Omniscape.OmniscapeFlags, ::Dict{String,String}, ::Circuitscape.RasterFlags, ::Circuitscape.OutputFlags, ::Array{Union{Missing, Float64},2}, ::Array{Union{Missing, Float64},2}, ::Array{Union{Missing, Float64},2}, ::Array{Union{Missing, Float64},2}, ::String, ::String, ::Float64, ::Float64, ::Float64, ::Float64, ::Array{Float64,2}, ::Array{Float64,3}, ::Array{Float64,3}, ::DataType) at C:\Users\rgrundel\.julia\packages\Omniscape\UilaE\src\utils.jl:507
 [7] macro expansion at C:\Users\rgrundel\.julia\packages\Omniscape\UilaE\src\main.jl:273 [inlined]
 [8] (::Omniscape.var"#71#threadsfor_fun#15"{Dict{String,Int64},DataType,Omniscape.OmniscapeFlags,String,String,Float64,Float64,Float64,Float64,Dict{String,String},Int64,Circuitscape.OutputFlags,Circuitscape.RasterFlags,ProgressMeter.Progress,Int64,UnitRange{Int64}})(::Bool) at .\threadingconstructs.jl:81
 [9] (::Omniscape.var"#71#threadsfor_fun#15"{Dict{String,Int64},DataType,Omniscape.OmniscapeFlags,String,String,Float64,Float64,Float64,Float64,Dict{String,String},Int64,Circuitscape.OutputFlags,Circuitscape.RasterFlags,ProgressMeter.Progress,Int64,UnitRange{Int64}})() at .\threadingconstructs.jl:48
Stacktrace:
 [1] wait at .\task.jl:267 [inlined]
 [2] threading_run(::Function) at .\threadingconstructs.jl:34
 [3] macro expansion at .\threadingconstructs.jl:93 [inlined]
 [4] run_omniscape(::Dict{String,String}, ::Array{Union{Missing, Float64},2}; reclass_table::Array{Union{Missing, Float64},2}, source_strength::Array{Union{Missing, Float64},2}, condition1::Array{Union{Missing, Float64},2}, condition2::Array{Union{Missing, Float64},2}, condition1_future::Array{Union{Missing, Float64},2}, condition2_future::Array{Union{Missing, Float64},2}, wkt::String, geotransform::Array{Float64,1}, write_outputs::Bool) at C:\Users\rgrundel\.julia\packages\Omniscape\UilaE\src\main.jl:268
 [5] top-level scope at REPL[6]:1
,

**Comment by vlandau** [comment] 2021-08-30 16:08
@linhunt thanks! @ranjanan looks like an issue with graph creation in Circuitscape?

**Comment by vlandau** [comment] 2021-08-30 16:11
@linhunt can you share your inputs via google drive or dropbox so we can reproduce and debug?

**Comment by linhunt** [comment] 2021-08-30 16:28
I sure can, the same inputs has produced multiple different errors this is one of the errors we have received, also that there are zero's/negative numbers but I have double checked and there aren't. The other possibly important thing is the inputs successfully ran Omniscape with a smaller block/radius, we are just receiving these errors at a large block/radius size, which doesn't on the surface seems odd but maybe it isn't.

**Comment by vlandau** [comment] 2021-08-30 16:30
Okay great thanks!

**Comment by ranjanan** [comment] 2022-12-29 19:08
Closing this, please feel free to reopen if this is still an issue

**Closed by ranjanan** 2022-12-29 19:08 UTC
