### ISSUE TITLE
Current file not written? Circuitscape runs, but has no output

### ISSUE THREAD

**Issue by merijnvdb** [Circuitscape/Circuitscape.jl#328] opened 2021-10-31 16:01 UTC
A few times now, using Arcmap 10.7 and the CS toolbox, I've tried to run circuitscape using 434 focal nodes which are points along the perimeter of the study area, that are rasterized. 

I try to uncheck writing current maps, and instead go for 'write cumulative current map only'.
Everything seems to run smoothly, in about one and a half hour all focal pairs are connected.
The only thing I find a little remarkable, is that arcmap states 'solving  focal node 'x' of 204', while it does recognize I have 434 focal nodes so I expected 217 pairs.

Anyways, when I then check my output folder, it has imported my resistance map and my focal nodes, both outside and inside of a 'scratch.gdb' folder. But other than that, there is nothing, no current map to be found.

Here's the execution description in Arcmap, as the Log is likely too long to post here;
Executing: Circuitscape "Pairwise: iterate across all pairs in focal node file" c8_res # nodesinraster # # C:\Natprop_euc\circuit\base false # "Connect EIGHT neighbors" true true # # # true # # # # #

Where c8_res is my resistance raster and 'nodesinraster' are my 434 perimeter points that are rasterized using the relevant function in the toolbox.

PS. I thought perhaps the 'write cum. current map only' may not be working so I tried it without, and while maps are written when I do this, the script tells me the progress window recognized there are 434 focal nodes but then it starts writing '1 out of 22421 nodes' or something. I of course can't have the tool write 20000 maps, so I cancel this run. Not sure what is going on here.

**Comment by vlandau** [comment] 2021-11-01 01:37
@merijnvdb Thanks for posting this issue. This appears to be a duplicate of #327. I'm going to close this issue so that we can track progress and debugging on #327. Please feel free to chime into the conversation there as we work to get this sorted! 

cc @ranjanan

**Closed by vlandau** 2021-11-01 01:37 UTC
