### ISSUE TITLE
AssertionError: norm(G * v .- curr, Inf) / norm(v, Inf) < 1.0e-5

### ISSUE THREAD

**Issue by PhilipFaure** [Circuitscape/Circuitscape.jl#345] opened 2022-01-17 11:46 UTC
Hi,

I am having trouble running Circuitscape. I have gone through the previous issues (open and closed) to see if any of the issues in there are similar or if their solutions could solve my problem, with no luck...

I trying to run a pairwise connectivity model between 67 observation points so that I can get one cumulative map with all possible connectivity. I am using the output of a species distribution ensemble model (.asc file format) as my habitat file, with `habitat_map_is_resistances = false` since the data resembles conductances. 

I keep getting the `AssertionError` and I have no idea what that means... Below is the printout from Julia, my INI file, and the packages with their versions currentl installed.

Thanks!

**Circuitscape and Julia version** 
Circuitscape v5.10.2 
Julia v1.6.2 (2021-07-14)

**Installed Julia package versions**
`GeoData 0.3.6`
`Omniscape 0.4.4`
`Circuitscape 5.10.2`
`SimpleWeightedGraphs 1.2.1`
`Plots 1.25.6`
Do I need some other package be installed?

This what prints out in Julia:
```julia
julia> compute("C:/Users/Vulpescana/Documents/Research/Blanfords_Fox/Circuitscape/model_config_pairwise.ini")
[ Info: 2022-01-17 13:06:47 : Precision used: Double
[ Info: 2022-01-17 13:06:47 : Starting up Circuitscape to use 3 processes in parallel
[ Info: 2022-01-17 13:06:59 : Reading maps
[ Info: 2022-01-17 13:07:12 : Resistance/Conductance map has 8968985 nodes
[ Info: 2022-01-17 13:07:19 : Solver used: AMG accelerated by CG
[ Info: 2022-01-17 13:07:21 : Graph has 8968985 nodes, 67 focal points and 30 connected components
[ Info: 2022-01-17 13:07:21 : Total number of pair solves = 2211
[ Info: 2022-01-17 13:07:36 : Time taken to construct preconditioner = 12.3121878 seconds
[ Info: 2022-01-17 13:07:38 : Time taken to construct local nodemap = 1.8730572 seconds
[ Info: 2022-01-17 13:07:57 : Scheduling pair 132 of 2211 to be solved
[ Info: 2022-01-17 13:07:57 : Scheduling pair 67 of 2211 to be solved
[ Info: 2022-01-17 13:07:57 : Scheduling pair 1 of 2211 to be solved
...
...
...
[ Info: 2022-01-17 13:07:58 : Scheduling pair 131 of 2211 to be solved
[ Info: 2022-01-17 13:07:58 : Solving pair 67 of 2211
[ Info: 2022-01-17 13:07:58 : Solving pair 1 of 2211
[ Info: 2022-01-17 13:07:58 : Solving pair 132 of 2211
ERROR: On worker 2:
AssertionError: norm(G * v .- curr, Inf) / norm(v, Inf) < 1.0e-5
Stacktrace:
 [1] solve_linear_system
   @ C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\core.jl:616
 [2] macro expansion
   @ .\timing.jl:287 [inlined]
 [3] f
   @ C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\core.jl:215
 [4] #97
   @ C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\core.jl:249
 [5] #106
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278
 [6] run_work_thunk
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:63
 [7] macro expansion
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278 [inlined]
 [8] #105
   @ .\task.jl:411
Stacktrace:
  [1] (::Base.var"#837#839")(x::Task)
    @ Base .\asyncmap.jl:177
  [2] foreach(f::Base.var"#837#839", itr::Vector{Any})
    @ Base .\abstractarray.jl:2141
  [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::UnitRange{Int64})
    @ Base .\asyncmap.jl:177
  [4] wrap_n_exec_twice
    @ .\asyncmap.jl:153 [inlined]
  [5] #async_usemap#822
    @ .\asyncmap.jl:103 [inlined]
  [6] #asyncmap#821
    @ .\asyncmap.jl:81 [inlined]
  [7] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Vector{Any}, retry_check::Nothing)
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:126
  [8] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:101
  [9] pmap(f::Function, c::UnitRange{Int64}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:156
 [10] pmap
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:156 [inlined]
 [11] solve(prob::Circuitscape.GraphProblem{Float64, Int64, Circuitscape.AMGSolver}, #unused#::Circuitscape.AMGSolver, flags::Circuitscape.RasterFlags, cfg::Dict{String, String}, log::Bool)
    @ Circuitscape C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\core.jl:249
 [12] single_ground_all_pairs (repeats 2 times)
    @ C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\core.jl:66 [inlined]
 [13] _pt_file_no_polygons_path(rasterdata::Circuitscape.RasterData{Float64, Int64}, flags::Circuitscape.RasterFlags, cfg::Dict{String, String})
    @ Circuitscape C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\raster\pairwise.jl:63
 [14] raster_pairwise(T::Type, V::Type, cfg::Dict{String, String})
    @ Circuitscape C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\raster\pairwise.jl:29
 [15] _compute(T::Type, V::Type, cfg::Dict{String, String})
    @ Circuitscape C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\run.jl:43
 [16] macro expansion
    @ .\timing.jl:287 [inlined]
 [17] compute(path::String)
    @ Circuitscape C:\Users\Vulpescana\.julia\packages\Circuitscape\QbA2E\src\run.jl:31
 [18] top-level scope
    @ REPL[4]:1
```

This is my INI file. Does this look correct?
```julia
[Circuitscape Mode]
data_type = raster
scenario = pairwise

[Version]
version = 5.10.2

[Habitat raster or graph]
habitat_file = C:\Users\Vulpescana\Documents\Research\Blanfords_Fox\Blanfords_Fox_SDM_code\BlanfordsSDM\Vulpes.cana\proj_EM_13012022\individual_projections\Vulpes.cana_EMmeanByROC_mergedAlgo_mergedRun_mergedData.asc
habitat_map_is_resistances = false

[Connection Scheme for raster habitat data]
connect_four_neighbors_only = false
connect_using_avg_resistances = false

[Short circuit regions (aka polygons)]
use_polygons = false
polygon_file = false

[Options for advanced mode]
ground_file_is_resistances = false
source_file = (Browse for a current source file)
remove_src_or_gnd = keepall
ground_file = (Browse for a ground point file)
use_unit_currents = false
use_direct_grounds = false

[Mask file]
use_mask = false
mask_file = None

[Options for one-to-all and all-to-one modes]
use_variable_source_strengths = false
variable_source_file = None

[Options for pairwise and one-to-all and all-to-one modes]
included_pairs_file = (Browse for a file with pairs to include or exclude)
use_included_pairs = false
point_file = C:\Users\Vulpescana\Documents\Research\Blanfords_Fox\Circuitscape\points.txt

[Output options]
write_cum_cur_map_only = true
log_transform_maps = false
output_file = current
write_max_cur_maps = false
write_volt_maps = false
set_null_currents_to_nodata = false
set_null_voltages_to_nodata = false
compress_grids = false
write_cur_maps = false

parallelize = true
max_parallel = 3
solver = cg+amg
```

**Comment by ranjanan** [comment] 2022-02-16 21:01
@PhilipFaure could you please attach your files so I can take a look?

**Comment by Mavisan6** [comment] 2022-02-20 19:17
I have the same exact problem, these are my files
https://drive.google.com/drive/folders/1a43zsbGXYkgDHdK8kdqYxehqwC-_2_sb?usp=sharing

**Comment by ranjanan** [comment] 2022-02-21 20:16
Thanks @Mavisan6 I'll take a look

**Comment by ranjanan** [comment] 2022-02-21 20:27
@Mavisan6 could you upload the habitat file? "ls_enfa.asc"

**Comment by Mavisan6** [comment] 2022-02-21 22:28
Hi! yes sorry actually I renamed it to conductance just to make it clearer for you, i forgot to rename it in the ini file

**Comment by BSiggery** [comment] 2022-02-23 17:04
Here is a link to my files https://drive.google.com/drive/folders/1x2KhASpIZLXiRO2FY89ye2rTd3jlrlf6?usp=sharing

**Comment by Mavisan6** [comment] 2022-03-02 16:34
@ranjanan did you manage to have a look?

**Comment by ranjanan** [comment] 2022-03-04 23:14
Thanks, #348 should fix this. When I merge that after tests, please check and confirm. @Mavisan6 @BSiggery

**Comment by ranjanan** [comment] 2022-03-05 02:37
Check now on master

**Comment by ranjanan** [comment] 2022-03-10 16:11
Closing this for now. Please reopen if there's an issue, or file a new one.

**Closed by ranjanan** 2022-03-10 16:11 UTC

**Comment by amatem** [comment] 2022-03-21 15:40
Hello, I recently received this assertion error on 3/19/22. Just wanted to note this (I did not copy the full code but here is the error I received from using pairwise mode cg+amg)

ERROR: On worker 2:
AssertionError: norm(G * v .- curr, Inf) / norm(v, Inf) < 1.0e-5
Stacktrace:
 [1] solve_linear_system
   @ C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:616
 [2] macro expansion
   @ .\timing.jl:287 [inlined]
 [3] f
   @ C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:215
 [4] #97
   @ C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:249
 [5] #106
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278
 [6] run_work_thunk
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:63
 [7] macro expansion
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278 [inlined]
 [8] #105
   @ .\task.jl:411
Stacktrace:
  [1] (::Base.var"#838#840")(x::Task)
    @ Base .\asyncmap.jl:177
  [2] foreach(f::Base.var"#838#840", itr::Vector{Any})
    @ Base .\abstractarray.jl:2141
  [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::UnitRange{Int64})
    @ Base .\asyncmap.jl:177
  [4] wrap_n_exec_twice
    @ .\asyncmap.jl:153 [inlined]
  [5] #async_usemap#823
    @ .\asyncmap.jl:103 [inlined]
  [6] #asyncmap#822
    @ .\asyncmap.jl:81 [inlined]
  [7] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Vector{Any}, retry_check::Nothing)
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:126
  [8] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:101
  [9] pmap(f::Function, c::UnitRange{Int64}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:156
 [10] pmap
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:156 [inlined]
 [11] solve(prob::Circuitscape.GraphProblem{Float64, Int64, Circuitscape.AMGSolver}, #unused#::Circuitscape.AMGSolver, flags::Circuitscape.RasterFlags, cfg::Dict{String, String}, log::Bool)
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:249
 [12] single_ground_all_pairs(prob::Circuitscape.GraphProblem{Float64, Int64, Circuitscape.AMGSolver}, flags::Circuitscape.RasterFlags, cfg::Dict{String, String}, log::Bool)
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:66
 [13] _pt_file_polygons_path(rasterdata::Circuitscape.RasterData{Float64, Int64}, flags::Circuitscape.RasterFlags, cfg::Dict{String, String})
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\raster\pairwise.jl:109
 [14] raster_pairwise(T::Type, V::Type, cfg::Dict{String, String})
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\raster\pairwise.jl:27
 [15] _compute(T::Type, V::Type, cfg::Dict{String, String})
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\run.jl:43
 [16] macro expansion
    @ .\timing.jl:287 [inlined]
 [17] compute(path::String)
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\run.jl:31
 [18] top-level scope
    @ REPL[4]:1

**Comment by ranjanan** [comment] 2022-03-21 15:43
@amatem could you mention which Circuitscape version you are on? The latest is 5.11.2

**Comment by amatem** [comment] 2022-03-21 16:25
> @amatem could you mention which Circuitscape version you are on? The latest is 5.11.2

Hello thank you this clued me into the potential version updates issue! I will need to communicate with IT at my research university to help update since this is running on a research server. I'll do that now and will follow up if the issue is resolved.

Circuitscape vv5.10.2
Julia v1.6.4 (2021-11-19)

julia> Pkg.add("Circuitscape")
    Updating registry at `C:\Users\amtemple\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
  No Changes to `C:\Users\amtemple\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\amtemple\.julia\environments\v1.6\Manifest.toml`
Precompiling project...
  ✗ Omniscape
  0 dependencies successfully precompiled in 28 seconds (69 already precompiled, 1 skipped during auto due to previous errors)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

**Comment by ranjanan** [comment] 2022-03-21 16:30
Ah interesting. Good luck updating this! If they could whitelist the Julia Registry you could just keep fetching the latest version everytime.

**Comment by amatem** [comment] 2022-03-21 17:55
> Ah interesting. Good luck updating this! If they could whitelist the Julia Registry you could just keep fetching the latest version everytime.

Still pending the completed run, but looks like the package dependency error was resolved for the time being

Our IT found that the profile disk was at its max quota. They resized it to 20 gigs. I'll run again and post if the AssertionError crops up again.

**Comment by amatem** [comment] 2022-03-22 17:01
Unfortunately I'm still received the Assertion Error after ensuring all packages were up to date. I've pasted an edited result below:

`julia> using Pkg

julia> Pkg.update("Circuitscape")
  Installing known registries into `C:\Users\amtemple\.julia`
     Cloning registry from "https://github.com/JuliaRegistries/General.git"
       Added registry `General` to `C:\Users\amtemple\.julia\registries\General`
    Updating registry at `C:\Users\amtemple\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
  No Changes to `C:\Users\amtemple\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\amtemple\.julia\environments\v1.6\Manifest.toml`

julia> Pkg.add("Circuitscape")
   Resolving package versions...
  No Changes to `C:\Users\amtemple\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\amtemple\.julia\environments\v1.6\Manifest.toml`

julia> Pkg.status
status (generic function with 8 methods)

julia> compute("I:\\Research\\Shares\\ocamp\\MCT\\individualnuthatch30m\\indivnuthatch58r30mt.ini")
ERROR: UndefVarError: compute not defined
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1

julia> using Circuitscape
[ Info: Precompiling Circuitscape [2b7a1792-8151-5239-925d-e2b8fdfa3201]
  Downloaded artifact: MKL

julia> compute("I:\\Research\\Shares\\ocamp\\MCT\\individualnuthatch30m\\indivnuthatch58r30mt.ini")
[ Info: 2022-03-21 10:52:03 : Precision used: Double
[ Info: 2022-03-21 10:52:03 : Starting up Circuitscape to use 1 processes in parallel
[ Info: 2022-03-21 10:52:28 : Reading maps
[ Info: 2022-03-21 10:52:52 : Resistance/Conductance map has 8227370 nodes
[ Info: 2022-03-21 10:53:00 : Total number of pair solves = 1711
[ Info: 2022-03-21 10:53:00 : Solving pair 1 of 1711
[ Info: 2022-03-21 10:53:18 : Solver used: AMG accelerated by CG
[ Info: 2022-03-21 10:53:20 : Graph has 8199987 nodes, 2 focal points and 3 connected components
[ Info: 2022-03-21 10:53:41 : Time taken to construct preconditioner = 19.2728731 seconds
[ Info: 2022-03-21 10:53:48 : Time taken to construct local nodemap = 7.0302814 seconds
[ Info: 2022-03-21 10:54:02 : Scheduling pair 1 of 1 to be solved
[ Info: 2022-03-21 10:55:06 : Time taken to solve linear system = 63.3836048 seconds
[ Info: 2022-03-21 10:55:18 : Time taken to calculate current maps = 12.0078728 seconds
.......................
[ Info: 2022-03-21 13:04:31 : Solving pair 58 of 1711
[ Info: 2022-03-21 13:06:01 : Solver used: AMG accelerated by CG
[ Info: 2022-03-21 13:06:01 : Graph has 1169019 nodes, 2 focal points and 1 connected components
[ Info: 2022-03-21 13:06:04 : Time taken to construct preconditioner = 3.2226783 seconds
[ Info: 2022-03-21 13:06:06 : Time taken to construct local nodemap = 1.6501147 seconds
[ Info: 2022-03-21 13:06:07 : Scheduling pair 1 of 1 to be solved
ERROR: On worker 2:
AssertionError: norm(G * v .- curr, Inf) / norm(v, Inf) < 1.0e-5
Stacktrace:
 [1] solve_linear_system
   @ C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:616
 [2] macro expansion
   @ .\timing.jl:287 [inlined]
 [3] f
   @ C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:215
 [4] #97
   @ C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:249
 [5] #106
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278
 [6] run_work_thunk
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:63
 [7] macro expansion
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:278 [inlined]
 [8] #105
   @ .\task.jl:411
Stacktrace:
  [1] (::Base.var"#838#840")(x::Task)
    @ Base .\asyncmap.jl:177
  [2] foreach(f::Base.var"#838#840", itr::Vector{Any})
    @ Base .\abstractarray.jl:2141
  [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::UnitRange{Int64})
    @ Base .\asyncmap.jl:177
  [4] wrap_n_exec_twice
    @ .\asyncmap.jl:153 [inlined]
  [5] #async_usemap#823
    @ .\asyncmap.jl:103 [inlined]
  [6] #asyncmap#822
    @ .\asyncmap.jl:81 [inlined]
  [7] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Vector{Any}, retry_check::Nothing)
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:126
  [8] pmap(f::Function, p::Distributed.WorkerPool, c::UnitRange{Int64})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:101
  [9] pmap(f::Function, c::UnitRange{Int64}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:156
 [10] pmap
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\pmap.jl:156 [inlined]
 [11] solve(prob::Circuitscape.GraphProblem{Float64, Int64, Circuitscape.AMGSolver}, #unused#::Circuitscape.AMGSolver, flags::Circuitscape.RasterFlags, cfg::Dict{String, String}, log::Bool)
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:249
 [12] single_ground_all_pairs(prob::Circuitscape.GraphProblem{Float64, Int64, Circuitscape.AMGSolver}, flags::Circuitscape.RasterFlags, cfg::Dict{String, String}, log::Bool)
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\core.jl:66
 [13] _pt_file_polygons_path(rasterdata::Circuitscape.RasterData{Float64, Int64}, flags::Circuitscape.RasterFlags, cfg::Dict{String, String})
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\raster\pairwise.jl:109
 [14] raster_pairwise(T::Type, V::Type, cfg::Dict{String, String})
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\raster\pairwise.jl:27
 [15] _compute(T::Type, V::Type, cfg::Dict{String, String})
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\run.jl:43
 [16] macro expansion
    @ .\timing.jl:287 [inlined]
 [17] compute(path::String)
    @ Circuitscape C:\Users\amtemple\.julia\packages\Circuitscape\QbA2E\src\run.jl:31
 [18] top-level scope
    @ REPL[7]:1

`

**Comment by jessjaco** [comment] 2022-07-25 17:14
I too am seeing this error with the latest version. Does anyone have insight on the cause? Is it due to the scale or range of values in the source or resistance layers? I suspect it may have to do with the precision setting (I am running in single), but I am not sure.

**Comment by ranjanan** [comment] 2022-07-25 17:25
Single precision may well give you this error. It is to do with the conditioning of the matrices being solved, which are to do in part with the range in values in the resistance grids.

**Comment by ranjanan** [comment] 2022-07-25 17:26
Does double work fine? I would suggest sticking with that.

**Comment by jessjaco** [comment] 2022-07-25 17:44
In this case I don't have the memory to run in single. I will do some subset tests and report back
